/*MIT License

Copyright (c) 2022 Eye-Mind Tool (Author: Amine Abbad-Andaloussi)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.*/
import { BrowserWindow, app, session } from 'electron'
import { REACT_DEVELOPER_TOOLS, installExtension } from 'electron-devtools-installer'
import electronSquirrelStartup from 'electron-squirrel-startup'
import { analysisListeners } from '@/app/listeners/analysis'
import { downloadListener } from '@/app/listeners/download'
import { eyeTrackerListeners } from '@/app/listeners/eye-tracker'
import { fileSetupListener } from '@/app/listeners/files-setup'
import {
  fixationFilterListeners,
  shutdownFixationFilterServer,
} from '@/app/listeners/fixation-filter'
import { testListeners } from '@/app/listeners/serverTests'
import { sessionListeners } from '@/app/listeners/session'
import { stateListeners } from '@/app/listeners/state'
import { windowListeners } from '@/app/listeners/window'

app.whenReady().then(() => {
  installExtension(REACT_DEVELOPER_TOOLS)
    .then((ext) => console.log(`Added Extension:  ${ext.name}`))
    .catch((err) => console.log('An error occurred: ', err))
})

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string
declare const MAIN_WINDOW_VITE_NAME: string
declare const MAIN_WINDOW_PRELOAD_VITE_NAME: string

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (Boolean(electronSquirrelStartup)) app.quit()

const createMainWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    // fullscreen: true,
    // resizable: false,
    autoHideMenuBar: true,
    title: 'EyeMind',
    show: false,
    /// frame: false,
    height: 800,
    width: 1400,
    minWidth: 800,
    minHeight: 500,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_VITE_NAME,
      // Allow loading files from local file system like images
      webSecurity: false,
      nodeIntegration: true,
    },
  })

  mainWindow.maximize()
  mainWindow.show()

  // used for the pop up windows
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url === 'about:blank') {
      return {
        action: 'allow',
        overrideBrowserWindowOptions: {
          frame: false,
          fullscreen: false,
          backgroundColor: '#E7EAED',
        },
      }
    }
    return { action: 'deny' }
  })

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL)
  } else {
    mainWindow.loadFile(MAIN_WINDOW_VITE_NAME)
  }

  // initiate set listeners
  stateListeners()

  // initiate window listeners
  windowListeners(mainWindow)

  // initiate fixation filter (R) listeners
  fixationFilterListeners(mainWindow)

  // initiate analysis listener
  analysisListeners(mainWindow)

  // initiate download listener
  downloadListener()

  // initiate file-setup listener
  fileSetupListener(mainWindow)

  // initiate eye-tracker listeners
  eyeTrackerListeners(mainWindow)

  // initiate session listeners
  sessionListeners()

  // initiate initiate test listeners
  testListeners()

  return mainWindow
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  session.defaultSession.allowNTLMCredentialsForDomains('*')

  let mainWindow = createMainWindow()

  const gotTheLock = app.requestSingleInstanceLock()

  if (!gotTheLock) {
    app.quit()
  } else {
    app.on('second-instance', () => {
      if (mainWindow.isMinimized()) mainWindow.restore()
      mainWindow.focus()
    })

    app.on('ready', () => {
      mainWindow = createMainWindow()
    })
  }
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', async () => {
  await shutdownFixationFilterServer()

  // quit electron app
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) createMainWindow()
})
